### ISSUE TITLE
Camera panning

### ISSUE THREAD

**Issue by Blitzy** [donmccurdy/glTF-Report-Feedback#10]
One of the projects I've worked on lately has consisted of dozens of complex architectural models that I've spent a lot of time optimizing for WebGL. Only having the ability to orbit and zoom limits my ability to compare the results of gltf.report script execution to the original input model, specifically for the interiors of these types of models.

Aspects like making sure that the DRACO compression settings are not causing unacceptable warping in vertex positions or texture coordinates is a little cumbersome right now as I have to load the model into another tool (like the three.js editor) to get the ability to inspect the model from otherwise unreachable angles.

I think adding the ability to pan the camera would enable enough control to be able to get the camera into almost any arbitrary position 😄

**Comment by donmccurdy** [comment]
Yes! I've been seeing this issue too, with models that are meant to be viewed from some interior viewpoint. Right now this site is simply using https://modelviewer.dev/ for the rendering portion — it's dead simple to install, and let me focus on the rest of the functionality — but it does have limited controls available. I'm curious if this example seems like it would do what you're hoping for?  https://modelviewer.dev/examples/stagingandcameras/#panning ... it seems "maybe helpful" but I'm a little skeptical it's the right setup.

Eventually I expect that this and other ideas (also see #1) will require me to replace model-viewer with something more custom, like https://github.com/donmccurdy/glTF-Transform-Render/, where I'll have full control of the panning and the render/update cycle, so that's probably the longer-term direction. 

For now I'd encourage you (and anyone else interested) to keep filing requests here and/or upvote existing ideas, I'm hoping to get a better idea of what people are looking for, before seeing how it should all fit together into design changes.

**Comment by Blitzy** [comment]
I think that model-viewer panning example does seem to get the job done. I can finagle the camera into viewing areas I want to look at that are otherwise currently unreachable. I think anything more advanced right now might be getting out of scope? I certainly love a good WASD fly-through camera but it has very specific use cases and is not a good general solution.

**Comment by donmccurdy** [comment]
For comparison, https://gltf-viewer.donmccurdy.com/ has a slightly different panning setup by default, and then also lets you disable "screen space panning" to pan along the horizontal plane instead. I think that functionality is better (although I might prefer model-viewer's damping a bit more?) but it doesn't exist in model-viewer yet.

**Comment by hybridherbst** [comment]
Btw, in case you're still using vanilla model-viewer, [there's an `enable-pan` attribute](https://modelviewer.dev/examples/stagingandcameras/#panning) now that does exactly that. Wouldn't really be my first choice for controls but it's a quick way to add it.

**Comment by donmccurdy** [comment]
Added in latest release —
![Screenshot 2022-11-13 at 11 54 16 PM](https://user-images.githubusercontent.com/1848368/201578340-03d48f58-c755-46b9-8047-f2fef947c546.png)

**Comment by donmccurdy** [comment]
Feel free to open a new issue yeah! I'd just note that this use OrbitControls and not model-viewer at this point, so any vanilla three.js references may be more helpful. It does feel to me like OrbitControls pans too slowly on large scenes, especially after zooming in a bit.
