### ISSUE TITLE
Idea: ability to open second view to compare two models with synchronized cameras

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Report-Feedback#16]
**Is your feature request related to a problem? Please describe.**
Often when working on compression, a need arises to compare models side-by-side (e.g. with/without etc1s).
This is relatively cumbersome given how small the differences can be.

**Describe the solution you'd like**
A nice feature for gltf.report would be that a second "pane" can be opened with synchronized camera view, so that Version 1 and Version 2 of a model (either created right in gltf.report, or dropped by the user) can be compared. The camera would exactly be synced. Future updates could include a "splitter" slider or similar to change view modes (or even a perceptual difference filter!).

**Describe alternatives you've considered**
Alternative solutions are simply opening two tabs with gltf.report, however that is lacking the camera sync and can't be extended towards better diff'ing and viewing.

**Comment by donmccurdy** [comment]
The Version 1 / "Base" and Version 2 / "Draft" concepts I originally included here are not particularly future-proof I'm afraid. I'd like to eventually support more UI editing (#1) and that would really benefit from complete undo/redo history rather than just reverting to a base version. I guess the two versioning approaches are not incompatible, but they're more complicated to combine.

An easy way to compare/diff two models would be really helpful though, I agree. Just need to think through how the versioning will work... 🤔

**Comment by donmccurdy** [comment]
Transferred to https://gltf-report.canny.io/feature-requests/p/comparison-with-beforeafter-3d-view.
