### ISSUE TITLE
Incorrect use of uv1, missing KHR_materials_volume

### ISSUE THREAD

**Issue by echadwick-wayfair** [donmccurdy/glTF-Report-Feedback#21]
**Describe the bug**
Some models seem to render with incorrect materials. Perhaps the renderer is applying uv1 incorrectly (uv1 is on the model but unused)? Also perhaps KHR_materials_volume is not supported?

**To Reproduce**
1. Go to https://gltf.report/
2. Drag-and-drop the attached model.
3. Notice the glossy blocky patches on the sides of the glass. The whole glass should appear shiny, rather than in blocks. Perhaps the textures are using uv1 instead of uv0? This model has an unused uv1.
4. Also notice the green attenuationColor is not appearing on the model. Perhaps KHR_materials_volume is not supported?

**Expected behavior**
The model should look similar to how it renders in the glTF Sample Viewer. https://github.khronos.org/glTF-Sample-Viewer-Release/ 

**Screenshots**
![image](https://user-images.githubusercontent.com/40177036/160483252-457b1a65-a6b0-4ccd-8b07-4c33363b103e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome
 - Version: 99.0.4844.84 (Official Build) (64-bit)

**Additional context**
Example model: [bzv4229_lod3.zip](https://github.com/donmccurdy/glTF-Report-Feedback/files/8366107/bzv4229_lod3.zip)

Thanks Don!

**Comment by donmccurdy** [comment]
Thanks @echadwick-wayfair! Two issues happening here — 

1. three.js always uses UV2 for AO. It detects when UV2 is missing and copies UV1, but isn't doing that here because it would be overwriting the existing (unused) UV2. So the AO is rendered with the wrong UVs causing the black splotches.
    - Resolution: Blocked by https://github.com/mrdoob/three.js/issues/12608
2. This viewer currently does not set a clear color (or other background) in the WebGL context, so you see the transparent HTML/CSS page behind the model. Since that CSS is outside the WebGL scope it doesn't get the expected attenuation.
    - Resolution: I believe this can be fixed with changes to this viewer

**Comment by donmccurdy** [comment]
I pushed a fix for (2) and you should see attenuation now:

![Screen Shot 2022-04-01 at 10 48 35 AM](https://user-images.githubusercontent.com/1848368/161287486-d0ff3a5e-3615-45cc-a70c-7dc6914d6833.png)

This does identify a remaining issue – this viewer scales the content to a unit cube to fit the camera/viewport framing, which then affects the attenuation because the scale has changed. I think I'll need to fix the content staging for that.

**Comment by donmccurdy** [comment]
> This does identify a remaining issue – this viewer scales the content to a unit cube to fit the camera/viewport framing, which then affects the attenuation (darker, above) because the scale has changed. I think I'll need to fix the content staging for that.

Fixed in latest release.

**Comment by donmccurdy** [comment]
Tracking the remaining parts of this issue in:

- https://github.com/donmccurdy/glTF-Report-Feedback/issues/36
