### ISSUE TITLE
Rendering Settings

### ISSUE THREAD

**Issue by vin-ni** [donmccurdy/glTF-Report-Feedback#24]
Hi,
the render and lightening settings look super good.
May I ask on a reference for your renderer and scene settings? I'd be interested in the environment settings as well.

Thank you very much!

**Comment by donmccurdy** [comment]
Hi! Mostly things are set up the same as in this three.js example...

https://github.com/mrdoob/three.js/blob/f0e2b3453f1412b53389beb04add414e3a80023c/examples/webgl_loader_gltf_compressed.html#L50-L62

... but with a couple changes:

1. I don't currently have `renderer.toneMapping` enabled
2. Instead of `THREE.RoomEnvironment` I'm using the environment here: https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/three-components/EnvironmentSceneAlt.ts

Alternatively, using https://modelviewer.dev/ will quickly give you very similar results out of the box.

**Comment by vin-ni** [comment]
Thank you!
