### ISSUE TITLE
Improve sidebar UX on mobile

### ISSUE THREAD

**Issue by hybridherbst** [donmccurdy/glTF-Report-Feedback#25]
**Describe the bug**
When loading a model on mobile (Android Chrome), the sidebar buttons stay grayed out. Not sure if this is intended (then hiding them might be more appropriate). Switching to desktop mode immediately makes them work again 

**To Reproduce**
1. Go to gltf.report on Android/Chrome
2. Load a model
3. Try to inspect textures or see validation results or run commands
4. Note Buttons are disabled
5. Switch to desktop page on mobile
6. Note Buttons are working

**Smartphone (please complete the following information):**
 - Device: Mi 9
 - OS: Android
 - Browser: Chrome
 - Version: 100.0

**Comment by donmccurdy** [comment]
Not the best solution but it is intentional... just not enough UI real estate to work on mobile without a lot of design investment. Also the [editor library](https://microsoft.github.io/monaco-editor/) is not great on mobile devices. Maybe some kind of tooltip when the buttons are pressed on mobile devices would be good.

**Comment by hybridherbst** [comment]
I'd actually be fine with the auto zoom behavior that mobiles do when screen real estate isn't enough, but I understand this might not be "native/integrated" enough for some users 🕵️

**Comment by donmccurdy** [comment]
I think this is likely to remain "view only" on mobile for the foreseeable future.
