### ISSUE TITLE
Why is disk size in stats different from disk size in Windows?

### ISSUE THREAD

**Issue by pkirsten** [donmccurdy/glTF-Report-Feedback#32]
The history stats window displays a disk size. I have noticed that is always different to the file size reported in my file explorer on Windows. 

I have tested this for example with the Astronaut of model-viewer:
[Astronaut.glb](https://github.com/google/model-viewer/blob/master/packages/shared-assets/models/Astronaut.glb)
- Model-viewer download page: 2.74 MB
- Windows: 2.73 MB
- GLTF.report: 2.9 MB

![20220912-224958-chrome](https://user-images.githubusercontent.com/38910969/189758989-e4b30307-7daa-4a66-bbac-aa92f2ac67f3.png)

I have other files with draco and KTX2 compression, which report for example 49.5 MB on Windows and 86.2 MB on GLTF.report. 

Maybe disk size means something different here, so I'm curious as to what the stats really calculate.

**Comment by donmccurdy** [comment]
Hi @pkirsten! The disk size metric is a running estimate of uncompressed file size on disk. The application has capabilities to edit glTF files (see: script tab), and to export with compression. Providing an exact measurement of disk size would require actually serializing the file after each change, or applying compression, which is quite expensive.

Admittedly it would probably be best if at least the _initial_ value of the disk size metric (before any changes are made) were based on the actual size of the input file, rather than an estimate, but that distinction isn't made today.

**Comment by donmccurdy** [comment]
Perhaps this would be better labeled "cpu" or "memory", to indicate that it won't necessarily match disk size, and that it doesn't consider any over-the-wire compression.
